groups:
- jobs:
  - build-arm64
  - build-amd64
  name: build
- jobs:
  - pipeline
  name: pipeline-update
jobs:
- name: pipeline
  plan:
  - get: containerfiles
    trigger: true
  - file: containerfiles/certbot-dns/pipeline.yml
    set_pipeline: img-certbot-dns
- name: build-arm64
  on_error:
    params:
      channel: '#build'
      alert_type: 'errored'
    put: notify
  on_failure:
    params:
      channel: '#build'
      alert_type: 'failed'
    put: notify
  on_success:
    params:
      channel: '#build'
      alert_type: 'success'
    put: notify
  plan:
  - get: containerfiles
    passed:
    - pipeline
    trigger: true
  - get: every-monday
    trigger: true
  - config:
      image_resource:
        source:
          repository: python
          tag: 3-slim
        type: registry-image
      inputs:
      - name: containerfiles
      outputs:
      - name: tags
      platform: linux
      run:
        args:
        - -euxc
        - VERSION=$(pip3 index versions certbot 2>/dev/null | grep certbot | cut -d'(' -f2 | cut -d')' -f1);
          if [[ "$VERSION" != "" ]]; then echo "$VERSION" >> tags/tags; else exit 1; fi;
        path: bash
    task: tag
    tags: [arm64]
  - config:
      image_resource:
        source:
          repository: rdclda/concourse-oci-build-task
        type: registry-image
      inputs:
      - name: containerfiles
      outputs:
      - name: image
      params:
        CONTEXT: containerfiles/certbot-dns
      platform: linux
      run:
        path: build
    privileged: true
    task: build-arm64
    tags: [arm64]
  - params:
      image: image/image.tar
      additional_tags: tags/tags
    put: thatsamguy-registry-arm64
    tags: [arm64]
- name: build-amd64
  on_error:
    params:
      channel: '#build'
      alert_type: 'errored'
    put: notify
  on_failure:
    params:
      channel: '#build'
      alert_type: 'failed'
    put: notify
  on_success:
    params:
      channel: '#build'
      alert_type: 'success'
    put: notify
  plan:
  - get: containerfiles
    passed:
    - pipeline
    trigger: true
  - get: every-monday
    trigger: true
  - config:
      image_resource:
        source:
          repository: python
          tag: slim
        type: registry-image
      inputs:
      - name: containerfiles
      outputs:
      - name: tags
      platform: linux
      run:
        args:
        - -euxc
        - VERSION=$(pip3 index versions certbot 2>/dev/null | grep certbot | cut -d'(' -f2 | cut -d')' -f1);
          if [[ "$VERSION" != "" ]]; then echo "$VERSION" >> tags/tags; else exit 1; fi;
        path: bash
    task: tag
    tags: [amd64]
  - config:
      image_resource:
        source:
          repository: vito/oci-build-task
        type: registry-image
      inputs:
      - name: containerfiles
      outputs:
      - name: image
      params:
        CONTEXT: containerfiles/certbot-dns
      platform: linux
      run:
        path: build
    privileged: true
    task: build-amd64
    tags: [amd64]
  - params:
      image: image/image.tar
      additional_tags: tags/tags
    put: thatsamguy-registry-amd64
    tags: [amd64]
resource_types:
- name: slack-alert
  type: docker-image
  source:
    repository: arbourd/concourse-slack-alert-resource
resources:
- icon: github
  name: containerfiles
  source:
    branch: main
    password: ((github-password))
    private_key: ((github-private-key))
    uri: git@github.com:thatsamguy/containerfiles.git
    username: ((github-username))
    paths:
    - certbot-dns/**
  type: git
- icon: slack
  name: notify
  type: slack-alert
  source:
    url: ((slack-webhook))
- icon: docker
  name: thatsamguy-registry-amd64
  source:
    repository: registry.thatsamguy.com/thatsamguy/certbot-dns
    tag: latest
  type: registry-image
- icon: docker
  name: thatsamguy-registry-arm64
  source:
    repository: registry.thatsamguy.com/thatsamguy/certbot-dns-arm64
    tag: latest
  type: registry-image
- icon: clock-outline
  name: every-monday
  source:
    days:
    - Monday
    location: Australia/Melbourne
    start: 12:00 AM
    stop: 5:00 AM
  type: time
