groups:
- jobs:
  - build-and-push
  name: build
- jobs:
  - pipeline
  name: pipeline-update
jobs:
- name: pipeline
  plan:
  - get: containerfiles
    trigger: true
  - file: containerfiles/certbot-dns/pipeline.yml
    set_pipeline: img-certbot-dns
- name: build-and-push
  on_error:
    params:
      channel: '#build'
      icon_url: https://concourse-ci.org/images/trademarks/concourse-black.png
      silent: true
      text: |
        :boom: A build of $BUILD_PIPELINE_NAME errored. Check it out <((ci-url))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|here>.
      username: concourse
    put: notify
  on_failure:
    params:
      channel: '#build'
      icon_url: https://concourse-ci.org/images/trademarks/concourse-black.png
      silent: true
      text: |
        :boom: A build of $BUILD_PIPELINE_NAME failed. Check it out <((ci-url))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|here>.
      username: concourse
    put: notify
  on_success:
    params:
      channel: '#build'
      icon_url: https://concourse-ci.org/images/trademarks/concourse-black.png
      silent: true
      text: |
        :airplane_departure: A new build of $BUILD_PIPELINE_NAME deployed! Check it out <((ci-url))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|here>.
      username: concourse
    put: notify
  plan:
  - get: containerfiles
    passed:
    - pipeline
    trigger: true
  - get: every-monday
    trigger: true
  - config:
      image_resource:
        source:
          repository: clearlinux/python
          tag: latest
        type: registry-image
      inputs:
      - name: containerfiles
      outputs:
      - name: tags
      platform: linux
      run:
        args:
        - -euxc
        - VERSION=$(pip3 install certbot && pip3 list certbot --format freeze | grep certbot | cut -d'=' -f3);
          if [[ "$VERSION" != "" ]]; then echo "$VERSION" >> tags/tags; else exit 1; fi;
        path: bash
    task: tag
  - config:
      image_resource:
        source:
          repository: vito/oci-build-task
        type: registry-image
      inputs:
      - name: containerfiles
      outputs:
      - name: image
      params:
        CONTEXT: containerfiles/certbot-dns
      platform: linux
      run:
        path: build
    privileged: true
    task: build
  - params:
      image: image/image.tar
      additional_tags: tags/tags
    put: dockerhub
  - params:
      image: image/image.tar
      additional_tags: tags/tags
    put: thatsamguy-registry
resource_types:
- name: slack-notification
  source:
    repository: cfcommunity/slack-notification-resource
  type: docker-image
resources:
- icon: github
  name: containerfiles
  source:
    branch: main
    password: ((github-password))
    private_key: ((github-private-key))
    uri: git@github.com:thatsamguy/containerfiles.git
    username: ((github-username))
    paths:
    - certbot-dns/**
  type: git
- icon: slack
  name: notify
  source:
    url: ((slack-webhook))
  type: slack-notification
- icon: docker
  name: dockerhub
  source:
    password: ((dockerhub-accesstoken))
    repository: thatsamguy/certbot-dns
    username: ((dockerhub-username))
    tag: latest
  type: registry-image
- icon: docker
  name: thatsamguy-registry
  source:
    repository: registry.thatsamguy.com/thatsamguy/certbot-dns
  type: registry-image
- icon: clock-outline
  name: every-monday
  source:
    days:
    - Monday
    location: Australia/Melbourne
    start: 12:00 AM
    stop: 5:00 AM
  type: time
