groups:
- jobs:
  - build-and-push
  name: build
- jobs:
  - pipeline
  name: pipeline-update
jobs:
- name: pipeline
  plan:
  - get: containerfiles
    trigger: true
  - file: containerfiles/certbot-dns/pipeline.yml
    set_pipeline: img-certbot-dns
- name: build-and-push
  on_error: &failure
    params:
      channel: '#build'
      icon_url: https://concourse-ci.org/images/trademarks/concourse-black.png
      silent: true
      text: |
        :boom: $BUILD_JOB_NAME of $BUILD_PIPELINE_NAME failed. <((ci-url))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Check it out>.
      username: concourse
    put: notify
    tags: [amd64]
  on_failure: *failure
  on_success: &success
    params:
      channel: '#build'
      icon_url: https://concourse-ci.org/images/trademarks/concourse-black.png
      silent: true
      text: |
        :airplane_departure: $BUILD_JOB_NAME of $BUILD_PIPELINE_NAME completed! <((ci-url))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Check it out>.
      username: concourse
    put: notify
    tags: [amd64]
  plan:
  - get: containerfiles
    passed:
    - pipeline
    trigger: true
  - get: every-monday
    trigger: true
  - config:
      image_resource:
        source:
          repository: python
          tag: slim
        type: registry-image
      inputs:
      - name: containerfiles
      outputs:
      - name: tags
      platform: linux
      run:
        args:
        - -euxc
        - pip3 install certbot;
          VERSION=$(pip3 list certbot --format freeze | grep certbot | cut -d'=' -f3);
          if [[ "$VERSION" != "" ]]; then echo "$VERSION" >> tags/tags; else exit 1; fi;
        path: bash
    task: tag
  - in_parallel:
    - config:
        image_resource:
          source:
            repository: rdclda/concourse-oci-build-task #vito/oci-build-task
          type: registry-image
        inputs:
        - name: containerfiles
        outputs:
        - name: image
        params:
          CONTEXT: containerfiles/certbot-dns
        platform: linux
        run:
          path: build
      privileged: true
      task: build-arm64
      tags: [arm64]
    - params:
        image: image/image.tar
        additional_tags: tags/tags
      put: thatsamguy-registry-arm64
      tags: [arm64]
    - config:
        image_resource:
          source:
            repository: vito/oci-build-task
          type: registry-image
        inputs:
        - name: containerfiles
        outputs:
        - name: image
        params:
          CONTEXT: containerfiles/certbot-dns
        platform: linux
        run:
          path: build
      privileged: true
      task: build-amd64
      tags: [amd64]
    - params:
        image: image/image.tar
        additional_tags: tags/tags
      put: thatsamguy-registry-amd64
      tags: [amd64]
resource_types:
- name: slack-notification
  source:
    repository: cfcommunity/slack-notification-resource
  type: docker-image
resources:
- icon: github
  name: containerfiles
  source:
    branch: main
    password: ((github-password))
    private_key: ((github-private-key))
    uri: git@github.com:thatsamguy/containerfiles.git
    username: ((github-username))
    paths:
    - certbot-dns/**
  type: git
- icon: slack
  name: notify
  source:
    url: ((slack-webhook))
  type: slack-notification
- icon: docker
  name: thatsamguy-registry-amd64
  source:
    repository: registry.thatsamguy.com/thatsamguy/certbot-dns
    tag: latest
  type: registry-image
- icon: docker
  name: thatsamguy-registry-arm64
  source:
    repository: registry.thatsamguy.com/thatsamguy/certbot-dns-arm64
    tag: latest
  type: registry-image
- icon: clock-outline
  name: every-monday
  source:
    days:
    - Monday
    location: Australia/Melbourne
    start: 12:00 AM
    stop: 5:00 AM
  type: time
